# Choose an agent virtual image
pool:
  vmImage: ubuntu-16.04
container:
  image: eschnett/cactus-amrex

steps:
- script: |
    set -euxo pipefail
    wget https://raw.githubusercontent.com/gridaphobe/CRL/ET_2019_03/GetComponents
    chmod a+x GetComponents
    ./GetComponents --parallel azure-pipelines/amrex.th
    echo 'docker' >$HOME/.hostname
    cp azure-pipelines/defs.local.ini Cactus/simfactory/etc
    cp azure-pipelines/docker.ini Cactus/simfactory/mdb/machines
    cp azure-pipelines/ubuntu.cfg Cactus/simfactory/mdb/optionlists
    cp azure-pipelines/docker.sub Cactus/simfactory/mdb/submitscripts
    cp azure-pipelines/docker.run Cactus/simfactory/mdb/runscripts
    mkdir $HOME/simulations
  displayName: Download Cactus
- script: |
    set -euxo pipefail
    cd Cactus
    ./simfactory/bin/sim build -j2 --thornlist=../azure-pipelines/amrex.th
  displayName: Build Cactus
- script: |
    set -euxo pipefail
    cd Cactus
    # ./simfactory/bin/sim run amrex --parfile=
    mpirun -np 2 -x OMP_NUM_THREADS=2 ./exe/cactus_sim ../azure-pipelines/amrex.par
  displayName: Run example
- script: |
    set -euxo pipefail
    cd Cactus
    env
    pwd
    ls -l
    ls -l ..
    ./simfactory/bin/sim submit sim-test --test --procs=1 --num-threads=2
    ./simfactory/bin/sim submit sim-test --test --procs=2 --num-threads=1
  displayName: Run tests
