version: '2'

volumes:
  homefs-cactusamrex:

services:
  cactus-amrex:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    image: einsteintoolkit/cactus-amrex-jovyan
    container_name: carpetx
    hostname: carpetx
    user: jovyan
    volumes:
      - homefs-cactusamrex:/home/jovyan
